// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBGe61ekvMG60bRH-6okDPVlRNqrvLBeM',
    appId: '1:115125146722:web:010b49e39cf173323a2d3b',
    messagingSenderId: '115125146722',
    projectId: 'chatapp-cd5c6',
    authDomain: 'chatapp-cd5c6.firebaseapp.com',
    storageBucket: 'chatapp-cd5c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRKgEe17w7mkjUA54ehVR6CIcHRcm-DSk',
    appId: '1:115125146722:android:03f062efa24bec5e3a2d3b',
    messagingSenderId: '115125146722',
    projectId: 'chatapp-cd5c6',
    storageBucket: 'chatapp-cd5c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv4EGa240enV0PM6681fVx0op3dahfZS8',
    appId: '1:115125146722:ios:1252402fa106c5583a2d3b',
    messagingSenderId: '115125146722',
    projectId: 'chatapp-cd5c6',
    storageBucket: 'chatapp-cd5c6.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
